services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: web_app
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql_db
        networks:
            - laravel

    web:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    mysql_db:
        image: mysql:8.4
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_DATABASE: islomnomoz
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3320:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

volumes:
    dbdata:

networks:
    laravel:
        driver: bridge
